### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by Roboxkin** [jindrapetrik/php-imagebw#1]
`<?php
require_once('imagebw.php');
$uploadfile =  basename($_FILES['filename']['name']);
if (move_uploaded_file($_FILES['filename']['tmp_name'], 'images/'.$uploadfile)) {
    function imagegreyscale($uploadfile): void;
} else {
    echo "Ошибка загрузки файла!";
}
`
<br />
<b>Parse error</b>:  syntax error, unexpected ';', expecting '{' in <b>E:\OSPanel\site.com\imageApi\Roboxtest\index.php</b> on line <b>7</b><br />

**Comment by jindrapetrik** [comment]
imagegreyscale function accepts resource|GdImage as a parameter.
The proper usage is something like:

```php
<?php
require_once('imagebw.php');
$img = imagecreatefromjpeg("inputfile.jpg");
imagegreyscale($img);
imagejpeg($img,"outputfile.jpg",99);
```

**Comment by Roboxkin** [comment]
Thank you very much!

**Comment by jindrapetrik** [comment]
You're welcome.
